<a href="https://colab.research.google.com/github/Aingon14/Datawerehouse-BigData/blob/main/02_Python101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Coding 🐍

In [20]:
print ("My first Python code!")
print ("Python is easier than I expected!!!")

My first Python code!
Python is easier than I expected!!!


To check your Python version and other extensions' version

In [21]:
!python --version

Python 3.10.12


In [22]:
!pip install --upgrade version_information
%load_ext version_information
%version_information numpy, scipy, matplotlib, sympy, version_information

The version_information extension is already loaded. To reload it, use:
  %reload_ext version_information


Software versions
Python 3.10.12 64bit [GCC 11.4.0]
IPython 7.34.0
OS Linux 5.15.109+ x86_64 with glibc2.35
numpy 1.23.5
scipy 1.10.1
matplotlib 3.7.1
sympy 1.12
version_information 1.0.4
Thu Sep 07 03:14:01 2023 UTC

To install this IPython extension

In [23]:
# you only need to do this once
!pip install --upgrade version_information

You may sometimes encounter this error. \
`ModuleNotFoundError: No module named 'pandas' in Python`

If you cannot import due to your computer cannot find, try installing the library using `pip install <library-name>`.

Begin the line with `!` to direct your code to command line

In [24]:
!pip install pandas

Help with functions

In [25]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [26]:
print(abs.__doc__)

Return the absolute value of the argument.


## Variables

ข้อกำหนดในการตั้งชื่อตัวแปร

* ชื่อห้ามมีเว้นวรรค
* (พยายาม)ใช้ภาษาอังกฤษ
* ตัวเล็กกับตัวใหญ่ แตกต่างกัน (case sensitive)
* ห้ามใช้ตัวเลขเป็นตัวหน้า

In [27]:
variable_a = 12
variable_b = 3.14
variable_c = "1" # ' (quote) หรือ " (double quote)
variable_d = 'Learning Pandas'
variable_e = True
variable_f = None

In [28]:
variable_ab = variable_a + variable_b
print(variable_ab)

15.14


In [29]:
print(type(variable_a))
print(type(variable_b))
print(type(variable_c))
print(type(variable_d))
print(type(variable_e))
print(type(variable_f))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>


Use functions: `int()`, `float()`, `str()`, `list()`, `tuple()`, `set()`, `complex()`, `ord()`, `hex()`, `oct()`, `dict()`, etc. to change type of object (type casting) in Python

In [30]:
print( float(variable_c), type(float(variable_c)) )

1.0 <class 'float'>


In [31]:
print(variable_c, type(variable_c))
new_c = int(variable_c)
print(new_c, type(new_c))

1 <class 'str'>
1 <class 'int'>


In [32]:
variable g = 1

SyntaxError: ignored

In [ ]:
x = 8
X = 1e-02
x == X

In [ ]:
y

## Operations

| Operator | Operation | Example |
|---|---|---|
| + | Addition | 5 + 2 = 7 |
| - | Subtraction | 4 - 2 = 2 |
| * | Multiplication | 2 * 3 = 6 |
| / | Division | 4 / 2 = 2 |
| // | Floor Division | 10 // 3 = 3 |
| % | Modulo | 5 % 2 = 1 |
| ** | Power | 4 ** 2 = 16 |

In [ ]:
print(-1, 2+3, 7%3, 7/2, 7//2, 2**4)

![order of operations](https://s3.amazonaws.com/cloudxlab/static/images/course/python-foundation-course/pemdas.png)

In [ ]:
43 + 13 - 9 / 3 * 7

| Operator | Name | Example |
|---|---|---|
| = | Assignment Operator | a = 7 |
| += | Addition Assignment | a += 1 # a = a + 1 |
| -= | Subtraction Assignment | a -= 3 # a = a - 3 |
| *= | Multiplication Assignment | a *= 4 # a = a * 4 |
| /= | Division Assignment | a /= 3 # a = a / 3 |
| %= | Remainder Assignment | a %= 10 # a = a % 10 |
| **= | Exponent Assignment | a **= 10 # a = a ** 10 |

In [ ]:
a = 10
b = 5

In [ ]:
a += b      # a = a + b
print(a)

In [ ]:
a *= b
print(a)

| Operator | Meaning | Example |
| --- | --- | --- |
| == | Is Equal To | 3 == 5 results in False |
| != | Not Equal To | 3 != 5 results in True |
| > | Greater Than | 3 > 5 results in False |
| < | Less Than | 3 < 5 results in True |
| >= | Greater Than or Equal To | 3 >= 5 results in False |
| <= | Less Than or Equal To | 3 <= 5 results in True |

In [ ]:
print(3 <= 4, 3 == 4, 3 != 4, 3 > 4)

In [ ]:
True == 1

In [ ]:
False == 0

In [ ]:
2 == 2.000000

In [ ]:
2 == 2.0000000000000000001

In [ ]:
2 == 2.001

In [ ]:
import math
help(math.isclose)

In [ ]:
math.isclose(2, 2.001, rel_tol=1e-03)

| Operator | Example | Meaning |
|---|---|---|
| and | a and b | True only if both the operands are True |
| or | a or b | True if at least one of the operands is True |
| not | not a | True if the operand is False and vice-versa |
| is | x is True | True if the operands are identical |
| is not | x is not True | True if the operands are not identical |
| in | 5 in x | True if value/variable is found in the sequence |
| not in | 5 not in x | True if value/variable is not found in the sequence |

In [ ]:
(3 < 8) is True

In [ ]:
print(True and True, False or True)

`x = 10` (0000 1010 in binary) and `y = 4` (0000 0100 in binary)

| Operator | Meaning | Example |
| --- | --- | --- |
| & | Bitwise AND | x & y = 0 (0000 0000) |
| \| | Bitwise OR | x \| y = 14 (0000 1110) |
| ~ | Bitwise NOT | ~x = -11 (1111 0101) |
| ^ | Bitwise XOR | x ^ y = 14 (0000 1110) |
| >> | Bitwise right shift | x >> 2 = 2 (0000 0010) |
| << | Bitwise left shift | x << 2 = 40 (0010 1000) |

In [ ]:
print(True & False, True | False)

## Containers (Collections)

In [ ]:
a_tuple = (1, 2, 3, 4)
a_list = ['a', 'b', 'c', 'd']   #ค่าอาจจะเป็นตัวเลขก็ได้
a_set = {1, 2, 2, 3, 3, 3}
a_dict = {'c': 1, 'b': 2, 'a': 3}

### Tuple

In [ ]:
print("The length of a_tuple:", a_tuple, "is", len(a_tuple))  #len -> หา length

Access element in tuple or list using the name of tuple or list variable following by *square brackets* <p>
<center>`tuple_or_list_var[index]`</center>

* Index starts with zero
* Final feasible index is (length - 1)
* Negative index reverses the position from -1 to -(length)

In [ ]:
print("a_tuple:", a_tuple)
print("values in each index", a_tuple[0], a_tuple[1], a_tuple[2], a_tuple[3])
print("values in each reverse index", a_tuple[-1], a_tuple[-2], a_tuple[-3], a_tuple[-4])
print("length of a_tuple", len(a_tuple))
print(a_tuple[len(a_tuple)])

<font color='red'><h4>📝 Your turn</h4></font>
```
myTuple = (12,123,12,12,1)
```
Get the element `123` from `myTuple`


In [ ]:
myTuple = (12,123,12,12,1)
myTuple

In [ ]:
# Get the element 123 from myTuple
myTuple[1]

In [ ]:
# Last element
myTuple[4]
myTuple[-1]

<font color='red'><h4>📝 Your turn</h4></font>
```
myTuple = (1,12,123,1234,12345)
```
Get the element `123` from `myTuple`

In [ ]:
myTuple = (1,12,123,1234,12345)
myTuple

In [ ]:
myTuple[2]   #index ที่ 2

In [ ]:
# Last element
myTuple[4]
myTuple[-1]

### List

Working with list is similar to tuple

In [ ]:
print("a_list:", a_list)

In [ ]:
len(a_list)

In [ ]:
a_list[0]

In [ ]:
a_list[-1]

In [ ]:
a_list.index('b')   #ดูว่า b อยู่ index ที่เท่าไหร่

In [ ]:
[i for i in range(len(a_list)) if a_list[i] == 'b' ]

In [ ]:
[i if a_list[i] == 'b' else  a_list for i in range(len(a_list)) ]   #ทำให้เหมือนอาจาร

To display multiple elements:
* Using `list[i:j]` to display element i$^\text{th}$ to (j-1)$^\text{th}$

In [ ]:
a_list[1:3]

* Iterating over a list

In [ ]:
[a_list[i] for i in [0,2]]

Adding an element to a list

In [ ]:
a_list.append('e')
a_list

Adding two lists concatenates them together

In [ ]:
a_list + a_list

In [ ]:
a_list + ['u', 'i']

Multiplying a list with an integer `n` creates a repeatation of a list `n` times

In [ ]:
[1,3]*3

String is a list of characters. Therefore, working with string is similar to list.

In [ ]:
variable_d

In [ ]:
print(variable_d[0])
print(variable_d[1:8])
print(variable_d[1:(variable_d.index('g')+1)])
print(variable_d[-1])
print(variable_d[1:])

In [ ]:
print(variable_d[:8])

In [ ]:
variable_d[0:2]

In [ ]:
'Keep ' + variable_d

<font color='red'><h4>📝 Your turn</h4></font>
```
variable_f = "Walking a corgi in the park"
```


In [34]:
variable_f = "Walking a corgi in the park"

In [37]:
variable_f[10:15]

'corgi'

In [ ]:
# get the character "P" from variable_d
variable_d[9]
Pindex = variable_d.index("P")
Pindex
variable_d[Pindex]

In [ ]:
# get the word "Pandas" from variable_d
variable_d[9:]
variable_d[9:15]


#### Advance list slicing
* Using [start_index:end_index:step]

In [38]:
variable_d

'Learning Pandas'

In [39]:
variable_d[::]

'Learning Pandas'

In [40]:
variable_d[::2] # display using step of 2

'Lann ads'

In [41]:
variable_d[::-1] # reversing a list

'sadnaP gninraeL'

* `range(start_value, final_value, step)`

In [42]:
variable_d[::3]

'LrnPd'

In [45]:
list(range(11))[::2]   #list step ทีละ 2

[0, 2, 4, 6, 8, 10]

In [46]:
list(range(0,12))[::2]

[0, 2, 4, 6, 8, 10]

In [47]:
range(0,4)

range(0, 4)

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [48]:
list(range(1,5,1))

[1, 2, 3, 4]

In [49]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

* `range(n)` = `range(0, n, 1)`

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

`map(func, *iterables)` --> Make an iterator that computes the function using arguments from each of the iterables.  Stops when the shortest iterable is exhausted.

In [52]:
list(map(lambda x: x**2, range(5)))

[0, 1, 4, 9, 16]

### Set

In [53]:
print("a_set = {1, 2, 2, 3, 3, 3}")
print("a_set:", a_set)

a_set = {1, 2, 2, 3, 3, 3}
a_set: {1, 2, 3}


In [54]:
len(a_set)

3

Casting set ot list

In [55]:
list(a_set)

[1, 2, 3]

In [56]:
list(a_set)[0]

1

### Dict

Python dictionary stores data in key-value format

In [57]:
print("a_dict = {'c': 1, 'b': 2, 'a': 3}")
print("a_dict:", a_dict)

a_dict = {'c': 1, 'b': 2, 'a': 3}
a_dict: {'c': 1, 'b': 2, 'a': 3}


In [58]:
a_dict.keys()

dict_keys(['c', 'b', 'a'])

In [59]:
a_dict.values()

dict_values([1, 2, 3])

In [60]:
len(a_dict)

3

In [61]:
a_dict.items()

dict_items([('c', 1), ('b', 2), ('a', 3)])

In [63]:
for item in a_dict.items():
  print("key of", key, "gives value of", val)

key of a gives value of 3
key of a gives value of 3
key of a gives value of 3


In [62]:
for key,val in a_dict.items():
    print("key of", key, "gives value of", val)

key of c gives value of 1
key of b gives value of 2
key of a gives value of 3


In [64]:
a_dict['c']

1

In [65]:
a_dict['a']

3

In [66]:
# add key "d" with value "4" to a_dict
a_dict["d"] = 4
a_dict

{'c': 1, 'b': 2, 'a': 3, 'd': 4}

<font color='red'><h4>📝 Your turn</h4></font>
<p>Create a dictionary from the following lists

```
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
```

In [67]:
# create my_dict
my_dict = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
my_dict['Twenty']

20

In [68]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
print("zip(keys,values):", zip(keys, values))
print("convert zip(keys,values) to list:", list(zip(keys, values)))
my_dict1 = dict(zip(keys, values))
my_dict1

zip(keys,values): <zip object at 0x789c7f605880>
convert zip(keys,values) to list: [('Ten', 10), ('Twenty', 20), ('Thirty', 30)]


{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

In [69]:
my_dict2 = {}
for i in range(len(keys)):
  my_dict2[keys[i]] = values[i]
my_dict2

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

## Vectors and Arrays

In [70]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (ในรูปแบบ matrix)

Create numpy array

In [71]:
np_a = np.array([[1,2,3],[4,5,6]])
np_a      #2*3

array([[1, 2, 3],
       [4, 5, 6]])

The size of a matrix can be accessed using `matrix.shape` resulting in (#rows,#columns)

In [72]:
np_a.shape   #กี่แถวกี่หลัก

(2, 3)

In [73]:
np_a.shape[0]

2

In [74]:
n_rows,n_cols = np_a.shape
print(n_rows, n_cols)

2 3


In [75]:
np_b = np.array([[1,4],[2,5],[3,6]])
print(np_b.shape)
np_b

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
np.random.randn(3,2)  #ถ้าจะฟิกค่าเดิมใช้ seed

array([[-0.58571578,  0.97552908],
       [ 2.53205003,  0.34906113],
       [-0.6699519 , -0.32741524]])

In [79]:
np.random.randint(0, 10, (3,2)) # random integers from 0 to 9

array([[2, 3],
       [7, 9],
       [5, 5]])

Indexing: [row,column] where using `:` as index means to select all elements in rows or columns

In [80]:
print(np_b)
np_b[0,1]

[[1 4]
 [2 5]
 [3 6]]


4

<font color='red'><h4>📝 Your turn</h4></font>

Retrieve the element `3` from `np_b`

In [81]:
# Retrieve the element 3 from np_b
np_b[2,0]


3

In [82]:
np_b[1]

array([2, 5])

In [83]:
np_b[1, :]

array([2, 5])

In [84]:
np_b[1:3, 1:]

array([[5],
       [6]])

Transpose matrix

In [85]:
np_b.T

array([[1, 2, 3],
       [4, 5, 6]])

matrix multiplication

In [86]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [88]:
np_a * np_b  #แต่ละmatrix ต้องมีแถวและหลักเท่ากัน

ValueError: ignored

In [89]:
np.dot(np_b,np_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [90]:
np.dot(np_a,np_b)

array([[14, 32],
       [32, 77]])

In [91]:
np_a.dot(np_b)

array([[14, 32],
       [32, 77]])

In [92]:
np_a * np_b

ValueError: ignored

In [93]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np_a * np_a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [95]:
np_a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [96]:
np_a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

Useful numpy functions

In [97]:
print(np_a)
np.sum(np_a)

[[1 2 3]
 [4 5 6]]


21

In [98]:
np.sum(np_a, axis=0)   #0 จะยุบแถวเป็น 1 แถว       ถ้า 1 จะยุบหลัก

array([5, 7, 9])

In [99]:
np.sum(np_a, axis=1)

array([ 6, 15])

In [100]:
np.mean(np_a)

3.5

In [108]:
np_a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [101]:
np.mean(np_a, axis=0) # compute mean along the row axes

array([2.5, 3.5, 4.5])

In [102]:
np.mean(np_a, axis=1) # compute mean along the column axes

array([2., 5.])

In [103]:
np_a.max(axis=0)

array([4, 5, 6])

## Pandas Series
One-dimensional ndarray with axis labels \
https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series

In [109]:
import pandas as pd

In [110]:
calories = {"day1": 420, "day2": 380, "day3": 390}
diet = pd.Series(calories)
#myseries = pd.Series([420, 380, 390], index=["day1","day2","day3"])
diet

day1    420
day2    380
day3    390
dtype: int64

In [111]:
diet["day2"]

380

In [112]:
diet[0]

420

In [113]:
diet.mean()

396.6666666666667

## Pandas Dataframe
Two-dimensional tabular data \
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame

### Creating a dataframe

![createDF](https://pbpython.com/images/pandas-dataframe-shadow.png)

In [114]:
import pandas as pd

In [115]:
d = {'No': [1, 2, 3, 4, 5],
     'Name': ["สมบูรณ์", "สมชาย", "สมหญิง", "สมหมาย", "สมบัติ"],
     'Age': [23, 45, 62, 30, 32]}
df = pd.DataFrame(data = d)
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3626 (\N{THAI CHARACTER SO SUA}) missing from current font.
  plt.savefig(
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3617 (\N{THAI CHARACTER MO MA}) missing from current font.
  plt.savefig(
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3594 (\N{THAI CHARACTER CHO CHANG}) missing from current font.
  plt.savefig(
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3634 (\N{THAI CHARACTER SARA AA}) missing from current font.
  plt.savefig(
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3618 (\N{THAI CHARACTER YO YAK}) missing from current font.
  plt.savefig(
/usr/local/lib/python3.10/dist-packages/google/colab/_quickchart_lib.py:26: UserWarning: Glyph 3610 (\N{THAI CHARACTER BO BAIMAI}) missing from cur

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['No'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['No'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['Age'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df, *['Name'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df, *[[['No', 'Age']]], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['No', 'Name'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['Age', 'Name'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df, *['No', 'Age', 'Name'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(df, *['No', 'count()', 'Name'], **{})
chart

In [116]:
!pip install pandas-profiling

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.3/357.3 kB 39.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 81.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 15.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.5/679.5 kB 50.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 35.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 109.9 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=65cd1810727dc9a35bfb5c5fd93d61b106f32d4a54ee6e0bdf36fd690baf69f9
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.2.1
    Uninstalling pydantic-2

In [117]:
from pandas_profiling import ProfileReport

In [120]:
profile = ProfileReport(df)
profile



Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [121]:
type(df)

pandas.core.frame.DataFrame

In [122]:
df.columns
#list(df.columns)

Index(['No', 'Name', 'Age'], dtype='object')

In [123]:
df.index
#list(df.index)

RangeIndex(start=0, stop=5, step=1)

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   No      5 non-null      int64 
 1   Name    5 non-null      object
 2   Age     5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [124]:
df.head()
#df.tail()

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [126]:
df.describe()

No        Age
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139  15.404545
min    1.000000  23.000000
25%    2.000000  30.000000
50%    3.000000  32.000000
75%    4.000000  45.000000
max    5.000000  62.000000

In [127]:
df.describe(include='all')

No     Name        Age
count   5.000000        5   5.000000
unique       NaN        5        NaN
top          NaN  สมบูรณ์        NaN
freq         NaN        1        NaN
mean    3.000000      NaN  38.400000
std     1.581139      NaN  15.404545
min     1.000000      NaN  23.000000
25%     2.000000      NaN  30.000000
50%     3.000000      NaN  32.000000
75%     4.000000      NaN  45.000000
max     5.000000      NaN  62.000000

### Selecting data

In [128]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [129]:
df["Name"] #series

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

In [130]:
df[["Name"]]   #dataframe

Name
0  สมบูรณ์
1    สมชาย
2   สมหญิง
3   สมหมาย
4   สมบัติ

In [131]:
df[["Name", "Age"]]

Name  Age
0  สมบูรณ์   23
1    สมชาย   45
2   สมหญิง   62
3   สมหมาย   30
4   สมบัติ   32

In [132]:
df["Name"]
#type(df["Name"]) # pandas.core.series.Series

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

![ilocvsloc](https://sparkbyexamples.com/wp-content/uploads/2021/10/pandas-difference-loc-vs-iloc.png)

In [133]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [135]:
df.loc[df['Age']>=40] #หาคนที่อายุมากกว่า 40

No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [136]:
df.loc[df['Age']>40,:]  #แบบนี้ก็ได้

No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [137]:
df[df["Age"]>40]  #นี่ก็ได้

No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [134]:
df.iloc[1,2]

45

In [138]:
df["Name"]=="สมหมาย"

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [139]:
df.loc[df["Name"]=="สมหมาย",:]
#df.loc[df["Name"]=="สมหมาย"]

No    Name  Age
3   4  สมหมาย   30

<font color='red'><h4>📝 Your turn</h4></font>

In [140]:
# Retrieve "สมหญิง" from df
df.iloc[2,1]
df.loc[df["Name"]=="สมหญิง","Name"]
df.loc[df["Name"]=="สมหญิง"]["Name"]

2    สมหญิง
Name: Name, dtype: object

In [141]:
# Get "Name" of people in df whose "Age" are less than 40 year's old
df.loc[df["Age"]<40,"Name"]




0    สมบูรณ์
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

## Controlling program flow

### Condition: if-elif-else

In [142]:
'a' if 3 < 4 else 'b'

'a'

In [143]:
'a' if 4 < 3 else 'b'

'b'

```python
if เงื่อนที่เราจะตรวจสอบ (โดยอาศัยสัญลักษณ์เหล่านี้ ==, !=, <, >, <=, >=, in, is_null()) :
    ถ้าเงื่อนไขเป็นจริง ทำ
```

In [144]:
if 1 < 5:
    print('yes')

yes


```python
if เงื่อนไขที่จะตรวจสอบ (โดยใช้สัญลักษณ์ ==,!=,<,>,<=,>=):
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b2
else: #ตรวจสอบเงื่อนไขข้างบนแล้วไม่เป็นจริง
    ทำงานที่ X
```
Note: จะไม่ `elif` หรือไม่มีก็ได้

In [146]:
import numpy as np

# random a real number between 60 to 100
score = np.random.uniform(60, 100)
print("score =", np.round(score,2))

if score > 90:
    print('A')
elif score > 80:
    print('B')
else:
    print('C')

score = 94.06
A


### Loop: for
```python
for ตัวแปรที่เราจะรับค่าจากลิสต์ in ลิสต์ที่ต้องการจะวนลูป:
    do something
    do another thing
this is outside the loop
```
Note: indent using 4 spaces

In [147]:
food = ['chiken', 'shabu', 'vegetable']

In [148]:
for i in food:
    print("I like to eat", i)

I like to eat chiken
I like to eat shabu
I like to eat vegetable


In [149]:
for i in range(10, 20, 2):
    print(i, i**2)

10 100
12 144
14 196
16 256
18 324


In [150]:
xs = []
for x in range(5):
    if x % 2 == 0:
        xs.append(x)
xs

[0, 2, 4]

## Using `for` loop to create a list

In [151]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [152]:
[x**2 for x in range(5) if x % 2 == 0]

[0, 4, 16]

In [153]:
[x**2 if x % 2 == 0 else -1 for x in range(5)]

[0, -1, 4, -1, 16]

### Loop: for, while
```python
while true_condition:
    do something
```
Note: indent using 4 spaces

In [154]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    count += 1

0
1
2
3
4


In [155]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    # break while loop if count = 3
    if count == 3:
        break
    count += 1

0
1
2
3


### Function
```python
def ชื่อฟังก์ชั่น(input1,input2,....):
    do something
    do another thing
    return output
```

In [ ]:
# Hello
# """
# Hello, my name is Meow!
# Hi!
# """

In [157]:
def f(x):
    """Say something about the function here."""
    return x

In [158]:
f

<function __main__.f(x)>

In [162]:
help(f)

Help on function f in module __main__:

f(x)
    Say something about the function here.



In [159]:
f("Hello Pythonions!")

'Hello Pythonions!'

In [160]:
f(3.14)

3.14

In [161]:
def compute_sum(a, b):
    """Calculate the sum of a and b."""
    return a + b

In [163]:
compute_sum(3,4)

7

In [164]:
def h(a= 0 , b = 1, c = 2):
    """Cacluates some complicated mathematical function."""
    return a + 2*b + 3*c

In [165]:
h()

8

In [166]:
h(1,1,2)

9

In [167]:
h(a=1)

9

In [168]:
h(c=3,b=2,a=1)

14

In [169]:
def func1(s):
    """
    Print a string 's' and tell how many characters it has
    s: a given string
    """
    print(s + " has " + str(len(s)) + " characters")

In [170]:
func1("Hello!")

Hello! has 6 characters


In [171]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Print a string 's' and tell how many characters it has
    s: a given string



## Using libraries

### math library

In [ ]:
import math
math.pi

3.141592653589793

In [ ]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [ ]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [ ]:
math.log(math.e)

1.0

In [ ]:
math.log(4)

1.3862943611198906

In [ ]:
math.log(4, 2)

2.0

### numpy library

In [ ]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
from numpy.random import rand
rand(4)

array([0.27369929, 0.06689894, 0.42373462, 0.73348517])

- Some other very useful modules form the Python standard library are `os`, `sys`, `shutil`, `re`, etc.
- A complete lists of standard modules for Python 3 is available at http://docs.python.org/3/library/